FROM ubuntu:18.04

LABEL maintainer="Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>"

ENV \
    # http://bugs.python.org/issue19846
    # > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
    # https://sourceware.org/bugzilla/show_bug.cgi?id=17318#c4
    # > set en_US.UTF-8 instead of C.UTF-8 because the former is not supported on all systems.
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8

ARG CMAKE_VERSION=3.31.8
ARG GIT_VERSION=2.50.1
ARG NINJA_VERSION=1.11.1.g95dee.kitware.jobserver-1
ARG PYTHON_VERSION=3.12.11

ARG AUTOMAKE_ROOT=automake-1.17
ARG AUTOMAKE_HASH=397767d4db3018dd4440825b60c64258b636eaf6bf99ac8b0897f06c89310acd
ARG AUTOMAKE_DOWNLOAD_URL=http://gnu.mirror.constant.com/automake/

ARG LIBTOOL_ROOT=libtool-2.5.3
ARG LIBTOOL_HASH=9322bd8f6bc848fda3e385899dd1934957169652acef716d19d19d24053abb95
ARG LIBTOOL_DOWNLOAD_URL=http://gnu.mirror.constant.com/libtool

ARG MAKE_ROOT=make-4.4
ARG MAKE_HASH=581f4d4e872da74b3941c874215898a7d35802f03732bdccee1d4a7979105d18
ARG MAKE_DOWNLOAD_URL=http://gnu.mirror.constant.com/make

ARG OPENSSL_VERSION=openssl-1.1.1w
ARG OPENSSL_HASH=cf3098950cb4d853ad95c0841f1f9c6d3dc102dccfcacd521d93925208b76ac8

ARG CURL_VERSION=curl-7.76.0
ARG CURL_HASH=3b4378156ba09e224008e81dcce854b7ce4d182b1f9cfb97fe5ed9e9c18c6bd3

ARG PERL_VERSION=perl-5.40.1
ARG PERL_HASH=02f8c45bb379ed0c3de7514fad48c714fd46be8f0b536bfd5320050165a1ee26

# Image build scripts
COPY \
  imagefiles/utils.sh \
  imagefiles/dockbuild-utils.sh \
  imagefiles/build-and-install-automake.sh \
  imagefiles/build-and-install-libtool.sh \
  imagefiles/build-and-install-make.sh \
  imagefiles/build-and-install-git.sh \
  imagefiles/build-and-install-python.sh \
  imagefiles/install-cmake-binary.sh \
  imagefiles/install-gosu-binary-wrapper.sh \
  imagefiles/install-ninja-binary.sh \
  /imagefiles/

ARG DEBIAN_FRONTEND=noninteractive

RUN \
  apt-get update && \
  \
  (LANG=C LANGUAGE=C LC_ALL=C apt-get install -y locales) && \
  locale-gen ${LANG%.*} ${LANG} && \
  \
  apt-get -y upgrade && \
  apt-get update && \
  apt-get install -y \
    build-essential \
    curl \
    gosu \
    openssh-client \
    pkg-config \
    unzip \
  && \
  # Needed to build Git from source
  apt-get install -y \
    gettext \
    libssl-dev \
    libcurl4-gnutls-dev \
    libexpat1-dev \
    zlib1g-dev \
  && \
  # Needed to build Python from source
  apt-get install -y \
    libbz2-dev \
    libffi-dev \
    liblzma-dev \
    libreadline-dev \
    libsqlite3-dev \
  && \
  #
  # Custom install
  #
  /imagefiles/install-cmake-binary.sh && \
  /imagefiles/install-gosu-binary-wrapper.sh && \
  /imagefiles/build-and-install-automake.sh && \
  /imagefiles/build-and-install-libtool.sh && \
  /imagefiles/build-and-install-make.sh && \
  /imagefiles/install-ninja-binary.sh && \
  /imagefiles/build-and-install-git.sh && \
  /imagefiles/build-and-install-python.sh && \
  rm -rf /imagefiles && \
  #
  # cleanup
  #
  rm -rf /var/lib/apt/lists/*

ENV AR=/usr/bin/ar \
    AS=/usr/bin/as \
    CC=/usr/bin/gcc \
    CPP=/usr/bin/cpp \
    CXX=/usr/bin/g++

#include "common.dockbuild"

#include "common.label-and-env"
